FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# NeighbourhoodCollaboration

Update and read the NeighbourhoodCollaboration database using the NBC api. 
There are three collections in the database with their own respective endpoints. 


For example, to GET a high level overview, use the /households endpoint.
This will return an array of all of the households: objects containing
their address and an array containing the names of the residents.

All post, put and update requests are handled by the /people endpoint.
For example, if we PUT a change to an existing person's address, our 
api will update the households. If this address did not previously exist
in the postcode collection, it will be added.

## Households Collection [/households/:id]

### List All Households [GET]

+ Response 200 (application/json)

        [
            {
                "address": "34 Jump Street",
                "residents": ["Bill Nox", "Jessica Shard"]
            }
        ]

### List Residents Of Household [GET]

+ Response 200 (application/json)

        {
            "address": "34 Jump Street",
            "residents": ["Bill Nox", "Jessica Shard"]
        }

## People Collection [/people/:id]
### List All People [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Jessica Shard",
                "age": 29,
                "people_in_household": 4,
                "address": "34 Jump Street, XYZ 95A"
            },
            {
                "name": "Bill Nox",
                "age": 31,
                "people_in_household": 4,
                "address": "34 Jump Street, XYZ 95A"
            }
        ]
        
### Get Person By ID

+ Response 200 (application/json)

            {
                "name": "Bill Nox",
                "age": 31,
                "people_in_household": 4,
                "address": "34 Jump Street, XYZ 95A"
            }

### Add New Person [POST]

+ Request (application/json)

        {
            "name": "David Brooker",
            "age": 28,
            "people_in_household": 4,
            "address": "34 Jump Street, XYZ 95A",
        }

+ Response 201 (application/json)

        {
            "message" : 
                "added David Brooker (28, living with 4 others at 34 Jump Street, XYZ 95A"
        }

### Change Existing Person [PUT]

+ Request (application/json)

        {
            "id": 2,
            "name": "David Lake-Brooker",
            "address": "64 Zoo Lane, XYZ 95A"
        }

+ Response 201 (application/json)

        {
            "message" : 
                "changed David Brooker name to David Lake-Brooker and address to 64 Zoo Lane, XYZ 95A"
        }

### Delete Existing Person [DELETE]

+ Request (application/json)

        {
            "id": 2
        }

+ Response 201 (application/json)

        {
            "message" : 
                "removed David Brooker from neighbourhood database"
        }

## Postcodes Collection [/postcodes/:postcode]
### List All Postcodes [GET]

+ Response 200 (application/json)

        [
            "XYZ 95A": ["34 Jump Street"],
            "XYZ 95B": ["64 Zoo Lane", "65 Zoo Lane"]
        ]
        
### List Addresses In Postcode [GET]

+ Response 200 (application/json)

        {
            "XYZ 95A": ["34 Jump Street"]
        }
