FORMAT: 1A
HOST: https://neighbourhoodCollaboration.com/

# neighbourhoodCollaboration

## Households Collection [/households]

### List all househoolds [GET]

+ Response 200 (application/json)

        [
            {
                "address": "123 Jon Street",
                "residients": ["name1", "name2", "name3"]
            }
        
        ]
        
    
## Households Collection [/households/:id]

### Get househoold by adress [GET]

+ Response 200 (application/json)

            {
                "address": "123 Jon Street",
                "residients": ["name1", "name2", "name3"]
            }
    

### Update household info [PUT]

+ Request 200 (application/json)

        [
            {
                "id": "id",
                "name": "Name1"
            }
        
        ]
        
+ Response 200 (application/json)

### Delete household [DELETE]

+ Request 200 (application/json)

        [
            {
                "address": "id"
            }
        
        ]
        
+ Response 200 (application/json)

## Postcodes Collection [/postcodes]

### List all postcodes [GET]

+ Response 200 (application/json)

        {
            "AD67 D12": ["213 Jon Street", "241 Jon Street"],
            "AD57 C12": ["563 Jon Street", "564 Jon Street"]
        }
        
## Postcodes Collection [/neighbourhood]

### Create a new database entry [POST]


+ Request (application/json)

        {
                "name": "Name1",
                "age": 23,
                "peopleHousehold": 4
                "address": "123 Jon Street, DA4 YB5",
        }

+ Response 201 (application/json)

    + Body

            {
                "message": "Data was successfully added to database"
            }
            
    
## People Collection [/people]

### List all people [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Name1",
                "age": 23,
                "peopleHousehold": 4
                "address": "123 Jon Street, DA4 YB5",
            }
        ]
        

### Update person's data [PUT]

+ Request 200 (application/json)

        {   
                "id": "id",
                "address": "123 Jon Street, DA4 YB5",
        }
        
    
+ Response 200 (application/json)

        {
            "message": "Data was successfully updated"
        }
        
        
### Delete person from database [DELETE]

+ Request 200 (application/json)

        
        {   
                "id": "id"
        }
        
        
+ Response 200 (application/json)

        {
            "message": "Data was sdeleted"
        }